name: Sync Docker Images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync-images-gcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: isrc-cas/image-sync-action@main
        with:
          auth_file: ./auth.yaml
          images_file: ./images-gcr.yaml
          version: latest
          proc: 1
        env:
          OEPKGS_HUB_PASSWORD: ${{ secrets.OEPKGS_HUB_PASSWORD }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  sync-images-nvcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: isrc-cas/image-sync-action@main
        with:
          auth_file: ./auth.yaml
          images_file: ./images-nvcr.yaml
          version: latest
          proc: 1
        env:
          OEPKGS_HUB_PASSWORD: ${{ secrets.OEPKGS_HUB_PASSWORD }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  sync-images-quay:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: isrc-cas/image-sync-action@main
        with:
          auth_file: ./auth.yaml
          images_file: ./images-quay.yaml
          version: latest
          proc: 1
        env:
          OEPKGS_HUB_PASSWORD: ${{ secrets.OEPKGS_HUB_PASSWORD }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  sync-images-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: isrc-cas/image-sync-action@main
        with:
          auth_file: ./auth.yaml
          images_file: ./images-ghcr.yaml
          version: latest
          proc: 1
        env:
          OEPKGS_HUB_PASSWORD: ${{ secrets.OEPKGS_HUB_PASSWORD }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  sync-images-docker-a-i:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: isrc-cas/image-sync-action@main
        with:
          auth_file: ./auth.yaml
          images_file: ./images-docker-a-i.yaml
          version: latest
          proc: 1
        env:
          OEPKGS_HUB_PASSWORD: ${{ secrets.OEPKGS_HUB_PASSWORD }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  sync-images-docker-j-n:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: isrc-cas/image-sync-action@main
        with:
          auth_file: ./auth.yaml
          images_file: ./images-docker-j-n.yaml
          version: latest
          proc: 1
        env:
          OEPKGS_HUB_PASSWORD: ${{ secrets.OEPKGS_HUB_PASSWORD }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  sync-images-docker-o-z:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: isrc-cas/image-sync-action@main
        with:
          auth_file: ./auth.yaml
          images_file: ./images-docker-o-z.yaml
          version: latest
          proc: 1
        env:
          OEPKGS_HUB_PASSWORD: ${{ secrets.OEPKGS_HUB_PASSWORD }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  sync-verify-images-quay:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: isrc-cas/image-sync-action@main
        with:
          auth_file: ./auth.yaml
          images_file: ./verify-images-quay.yaml
          version: latest
          proc: 1
        env:
          OEPKGS_HUB_PASSWORD: ${{ secrets.OEPKGS_HUB_PASSWORD }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  sync-verify-images-nvcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: isrc-cas/image-sync-action@main
        with:
          auth_file: ./auth.yaml
          images_file: ./verify-images-nvcr.yaml
          version: latest
          proc: 1
        env:
          OEPKGS_HUB_PASSWORD: ${{ secrets.OEPKGS_HUB_PASSWORD }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}