name: Sync Docker Images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: isrc-cas/image-sync-action@main
        with:
          auth_file: ./auth.yaml
          images_file: ./images.yaml
          version: latest
          proc: 20
        env:
          OEPKGS_HUB_PASSWORD: ${{ secrets.OEPKGS_HUB_PASSWORD }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}